image: Visual Studio 2017
environment:
  global:
    SONAR_KEY:
      secure: GbMflncwje+wnuVU8gtWsUctEOWNdUs2D1xRejCdqcrwmcGmEIW7jn1YAV8bgyk4 
      
      
install:
  - choco source
  - choco install gitversion.portable -pre -y
  - choco install codecov -y
  - dotnet tool install --global dotnet-sonarscanner

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo 
  - ps: Update-AppveyorBuild -Version "${env:GitVersion_NuGetVersion}"
  - cmd: dotnet sonarscanner begin /k:"ProcessStartAsync"  /d:sonar.organization="martinjarvis-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_KEY%" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="test/**" /d:sonar.projectVersion="%GitVersion_NuGetVersion%"
     
 
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal

after_build:
  - cmd: appveyor PushArtifact "ProcessStartAsync.%GitVersion_NuGetVersion%.nupkg"  

test_script:
  - cmd: dotnet test test/ProcessStartAsync.UnitTests/ProcessStartAsync.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

on_finish:
  - cmd: codecov -f test/ProcessStartAsync.UnitTests/coverage.opencover.xml
  - cmd: dotnet sonarscanner end /d:sonar.login="%SONAR_KEY%"