image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y
  - dotnet tool install --global dotnet-sonarscanner

assembly_info:
  patch: false

before_build:
  - nuget restore
  - cmd: dotnet sonarscanner begin /k:"ProcessStartAsync"  /d:sonar.organization="martinjarvis-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="GbMflncwje+wnuVU8gtWsUctEOWNdUs2D1xRejCdqcrwmcGmEIW7jn1YAV8bgyk4" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="test/**"
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo    
  - cmd: dotnet setversion %GitVersion_NuGetVersion%
 
build:
  publish_nuget: true
  verbosity: minimal

#after_build:
#  - cmd: ECHO nuget pack src\ProcessStartAsync\ProcessStartAsync.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#  - cmd: nuget pack src\ProcessStartAsync\ProcessStartAsync.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#  - cmd: appveyor PushArtifact "ProcessStartAsync.%GitVersion_NuGetVersion%.nupkg"
  
test_script:
- cmd: dotnet test test/ProcessStartAsync.UnitTests/ProcessStartAsync.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

on_finish:
- cmd: dotnet sonarscanner end /d:sonar.login="GbMflncwje+wnuVU8gtWsUctEOWNdUs2D1xRejCdqcrwmcGmEIW7jn1YAV8bgyk4"